# 必需项
version: 2

# 设置操作系统、Python 版本和其他工具
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# 使用 Sphinx 构建位于 "docs/" 目录中的文档
sphinx:
  configuration: source/conf.py

# 可选地将文档构建为其他格式，如 PDF 和 ePub
formats:
  - PDF

python:
  install:
    - requirements: requirements.txt
