# Required
version:2

# Set the 0S, Python version and other tools you might need
build:
  os:ubuntu-22.04
  tools:
    python:"3.11"


# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - PDF

python:
  install:
  - requirements: requirements.txt